version: '2.4'
services:
   db:
     image: mysql:5.7
     command: --default-authentication-plugin=mysql_native_password
     ports:
      - '3306:3306'
     expose:
      - '3306'    
     volumes:
      - './.mysql-data/db:/var/lib/mysql'
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: secret
     networks:
         - ingress

   manager:
     image: payara/server-full:5.191
     container_name: manager
     ports:
        - "18080:8080"
        - "14848:4848"
     environment:
        - ADMIN_USER=admin
        - ADMIN_PASSWORD=secret    
     depends_on:
            - db
     mem_limit: 2048m
     mem_reservation: 100m
     volumes:
     - ./deployments:/opt/payara/deployments
     networks:
         - ingress
         
   worker1:
     image: payara/server-full:5.191
     container_name: worker1
     mem_limit: 2048m
     mem_reservation: 100m
     ports:
        - "28080:8080"
        - "24848:4848"
     environment:
        - ADMIN_USER=admin
        - ADMIN_PASSWORD=secret    
     depends_on:
            - db
     volumes:
     - ./deployments:/opt/payara/deployments
     networks:
         - ingress
         
   worker2:
     image: payara/server-full:5.191
     container_name: worker2
     mem_limit: 2048m
     mem_reservation: 100m
     ports:
        - "38080:8080"
        - "34848:4848"
     environment:
        - ADMIN_USER=admin
        - ADMIN_PASSWORD=secret    
     depends_on:
            - db
     volumes:
     - ./deployments:/opt/payara/deployments
     networks:
        - ingress         
         
networks:
  mired:
    driver: macvlan
    ipam:
      config:
        - subnet: "192.168.0.1/24"
          gateway: "192.168.0.1"