version: '2.4'
services:
   db:
     image: mysql:5.7
     command: --default-authentication-plugin=mysql_native_password
     ports:
      - '3306:3306'
     expose:
      - '3306'    
     volumes:
      - './.mysql-data/db:/var/lib/mysql'
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: secret
  #   networks:
  #          mired:
  #              ipv4_address: 192.168.99.120

   payara:
     image: payara/server-full:5.191
     ports:
        - "8088:8080"
        - "4848:4848"
     environment:
        - ADMIN_USER=admin
        - ADMIN_PASSWORD=secret    
     depends_on:
            - db
     volumes:
     - ./deployments:/opt/payara/deployments
  #   networks:
  #          mired:
  #              ipv4_address: 192.168.99.120 
networks:
  mired:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.99.1/24"
          gateway: "192.168.99.1"