package modelo;
// Generated 09-10-2019 01:04:50 PM by Hibernate Tools 4.3.1

/**
 * EmpCtaBco generated by hbm2java
 */
public class EmpCtaBco implements java.io.Serializable {

    private Integer id;
    private String codEmpleado;
    private String nroCuenta;
    private byte snActiva;
    private EmpMae empMae;

    public EmpCtaBco() {
    }

    public EmpCtaBco(String codEmpleado, String nroCuenta, byte snActiva) {
        this.codEmpleado = codEmpleado;
        this.nroCuenta = nroCuenta;
        this.snActiva = snActiva;
    }

    public String getCodEmpleado() {
        return codEmpleado;
    }

    public void setCodEmpleado(String codEmpleado) {
        this.codEmpleado = codEmpleado;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNroCuenta() {
        return this.nroCuenta;
    }

    public void setNroCuenta(String nroCuenta) {
        this.nroCuenta = nroCuenta;
    }

    public byte getSnActiva() {
        return this.snActiva;
    }

    public void setSnActiva(byte snActiva) {
        this.snActiva = snActiva;
    }

}
