package modelo;
// Generated 09-10-2019 01:04:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EmpCtaBco generated by hbm2java
 */
public class EmpCtaBco  implements java.io.Serializable {


     private Integer id;
     private Tbanco tbanco;
     private Tmoneda tmoneda;
     private String nroCuenta;
     private byte snActiva;
   
    public EmpCtaBco() {
    }

	
    public EmpCtaBco(Tbanco tbanco, Tmoneda tmoneda, String nroCuenta, byte snActiva) {
        this.tbanco = tbanco;
        this.tmoneda = tmoneda;
        this.nroCuenta = nroCuenta;
        this.snActiva = snActiva;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tbanco getTbanco() {
        return this.tbanco;
    }
    
    public void setTbanco(Tbanco tbanco) {
        this.tbanco = tbanco;
    }
    public Tmoneda getTmoneda() {
        return this.tmoneda;
    }
    
    public void setTmoneda(Tmoneda tmoneda) {
        this.tmoneda = tmoneda;
    }
    public String getNroCuenta() {
        return this.nroCuenta;
    }
    
    public void setNroCuenta(String nroCuenta) {
        this.nroCuenta = nroCuenta;
    }
    public byte getSnActiva() {
        return this.snActiva;
    }
    
    public void setSnActiva(byte snActiva) {
        this.snActiva = snActiva;
    }
   



}


