package modelo;
// Generated 09-02-2019 10:41:42 PM by Hibernate Tools 4.3.1



/**
 * EmpMovimiento generated by hbm2java
 */
public class EmpMovimiento  implements java.io.Serializable {


     private Integer id;
     private EmpMae empMae;
     private TtipoMovimiento ttipoMovimiento;
     private double importe;
     private boolean snActivo;
     private boolean snAcumula;

    public EmpMovimiento() {
        this.empMae = new EmpMae();
        this.ttipoMovimiento = new TtipoMovimiento();
        this.id = 0;
        this.importe = 0;
        this.snActivo = true;
        this.snAcumula = false;
    }

    public EmpMovimiento(EmpMae empMae, TtipoMovimiento ttipoMovimiento, double importe, boolean snActivo, boolean snAcumula) {
       this.empMae = empMae;
       this.ttipoMovimiento = ttipoMovimiento;
       this.importe = importe;
       this.snActivo = snActivo;
       this.snAcumula = snAcumula;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EmpMae getEmpMae() {
        return this.empMae;
    }
    
    public void setEmpMae(EmpMae empMae) {
        this.empMae = empMae;
    }
    public TtipoMovimiento getTtipoMovimiento() {
        return this.ttipoMovimiento;
    }
    
    public void setTtipoMovimiento(TtipoMovimiento ttipoMovimiento) {
        this.ttipoMovimiento = ttipoMovimiento;
    }
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }
    public boolean isSnActivo() {
        return this.snActivo;
    }
    
    public void setSnActivo(boolean snActivo) {
        this.snActivo = snActivo;
    }
    public boolean isSnAcumula() {
        return this.snAcumula;
    }
    
    public void setSnAcumula(boolean snAcumula) {
        this.snAcumula = snAcumula;
    }




}


