package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * EmpMae generated by hbm2java
 */
public class EmpMae implements java.io.Serializable {

     private Integer id;
     private EmpCtaBco empCtaBco;
     private Tcargo tcargo;
     private TdeptoEmp tdeptoEmp;
     private TdeptoPais tdeptoPais;
     private TestadoCivil testadoCivil;
     private Tmunicipios tmunicipios;
     private Tpais tpais;
     private Tprofesion tprofesion;
     private TtipoDocumento ttipoDocumento;
     private TtipoEmpleado ttipoEmpleado;
     private String codEmpleado;
     private String primerApellido;
     private String segundoApellido;
     private String nombres;
     private String nroIdentidad;
     private Date fechaNac;
     private String lugarNacimiento;
     private char sexo;
     private BigDecimal sueldoBruto;
     private Date fecAlta;
     private Date fecBaja;
     private String creadoPor;
     private String modificadoPor;
     private Date fecModificado;
     private byte[] foto;
     private String tel1;
     private String tel2;
     private String correo1;
     private String correo2;

   
    public EmpMae() {

        /*
          Todas las tablas deben inicializars desde la tabla padre
          o Tabla principal en este caso es la tabla de empleados
          Las demas tablas no deben de inicializarse
         */
        this.tpais = new Tpais();
        this.tdeptoPais = new TdeptoPais();
        this.tmunicipios = new Tmunicipios();
        this.tcargo = new Tcargo();
        this.tprofesion = new Tprofesion();
        this.tdeptoEmp = new TdeptoEmp();
        this.testadoCivil= new TestadoCivil();
        this.ttipoEmpleado = new TtipoEmpleado();
        this.ttipoDocumento = new TtipoDocumento();
        this.empCtaBco = new EmpCtaBco();
        this.sexo = ' ';

    }

      public EmpMae(Tcargo tcargo, TdeptoEmp tdeptoEmp, TdeptoPais tdeptoPais, TestadoCivil testadoCivil, Tmunicipios tmunicipios, Tpais tpais, Tprofesion tprofesion, TtipoDocumento ttipoDocumento, TtipoEmpleado ttipoEmpleado, String codEmpleado, String primerApellido, String nombres, String nroIdentidad, Date fechaNac, char sexo, BigDecimal sueldoBruto, Date fecAlta, String creadoPor, String tel1, String correo1) {
        this.tcargo = tcargo;
        this.tdeptoEmp = tdeptoEmp;
        this.tdeptoPais = tdeptoPais;
        this.testadoCivil = testadoCivil;
        this.tmunicipios = tmunicipios;
        this.tpais = tpais;
        this.tprofesion = tprofesion;
        this.ttipoDocumento = ttipoDocumento;
        this.ttipoEmpleado = ttipoEmpleado;
        this.codEmpleado = codEmpleado;
        this.primerApellido = primerApellido;
        this.nombres = nombres;
        this.nroIdentidad = nroIdentidad;
        this.fechaNac = fechaNac;
        this.sexo = sexo;
        this.sueldoBruto = sueldoBruto;
        this.fecAlta = fecAlta;
        this.creadoPor = creadoPor;
        this.tel1 = tel1;
        this.correo1 = correo1;
    }
    public EmpMae(EmpCtaBco empCtaBco, Tcargo tcargo, TdeptoEmp tdeptoEmp, TdeptoPais tdeptoPais, TestadoCivil testadoCivil, Tmunicipios tmunicipios, Tpais tpais, Tprofesion tprofesion, TtipoDocumento ttipoDocumento, TtipoEmpleado ttipoEmpleado, String codEmpleado, String primerApellido, String segundoApellido, String nombres, String nroIdentidad, Date fechaNac, String lugarNacimiento, char sexo, BigDecimal sueldoBruto, Date fecAlta, Date fecBaja, String creadoPor, String modificadoPor, Date fecModificado, byte[] foto, String tel1, String tel2, String correo1, String correo2) {
       this.empCtaBco = empCtaBco;
       this.tcargo = tcargo;
       this.tdeptoEmp = tdeptoEmp;
       this.tdeptoPais = tdeptoPais;
       this.testadoCivil = testadoCivil;
       this.tmunicipios = tmunicipios;
       this.tpais = tpais;
       this.tprofesion = tprofesion;
       this.ttipoDocumento = ttipoDocumento;
       this.ttipoEmpleado = ttipoEmpleado;
       this.codEmpleado = codEmpleado;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.nombres = nombres;
       this.nroIdentidad = nroIdentidad;
       this.fechaNac = fechaNac;
       this.lugarNacimiento = lugarNacimiento;
       this.sexo = sexo;
       this.sueldoBruto = sueldoBruto;
       this.fecAlta = fecAlta;
       this.fecBaja = fecBaja;
       this.creadoPor = creadoPor;
       this.modificadoPor = modificadoPor;
       this.fecModificado = fecModificado;
       this.foto = foto;
       this.tel1 = tel1;
       this.tel2 = tel2;
       this.correo1 = correo1;
       this.correo2 = correo2;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EmpCtaBco getEmpCtaBco() {
        return this.empCtaBco;
    }
    
    public void setEmpCtaBco(EmpCtaBco empCtaBco) {
        this.empCtaBco = empCtaBco;
    }
    public Tcargo getTcargo() {
        return this.tcargo;
    }
    
    public void setTcargo(Tcargo tcargo) {
        this.tcargo = tcargo;
    }
    public TdeptoEmp getTdeptoEmp() {
        return this.tdeptoEmp;
    }
    
    public void setTdeptoEmp(TdeptoEmp tdeptoEmp) {
        this.tdeptoEmp = tdeptoEmp;
    }
    public TdeptoPais getTdeptoPais() {
        return this.tdeptoPais;
    }
    
    public void setTdeptoPais(TdeptoPais tdeptoPais) {
        this.tdeptoPais = tdeptoPais;
    }
    public TestadoCivil getTestadoCivil() {
        return this.testadoCivil;
    }
    
    public void setTestadoCivil(TestadoCivil testadoCivil) {
        this.testadoCivil = testadoCivil;
    }
    public Tmunicipios getTmunicipios() {
        return this.tmunicipios;
    }
    
    public void setTmunicipios(Tmunicipios tmunicipios) {
        this.tmunicipios = tmunicipios;
    }
    public Tpais getTpais() {
        return this.tpais;
    }
    
    public void setTpais(Tpais tpais) {
        this.tpais = tpais;
    }
    public Tprofesion getTprofesion() {
        return this.tprofesion;
    }
    
    public void setTprofesion(Tprofesion tprofesion) {
        this.tprofesion = tprofesion;
    }
    public TtipoDocumento getTtipoDocumento() {
        return this.ttipoDocumento;
    }
    
    public void setTtipoDocumento(TtipoDocumento ttipoDocumento) {
        this.ttipoDocumento = ttipoDocumento;
    }
    public TtipoEmpleado getTtipoEmpleado() {
        return this.ttipoEmpleado;
    }
    
    public void setTtipoEmpleado(TtipoEmpleado ttipoEmpleado) {
        this.ttipoEmpleado = ttipoEmpleado;
    }
    public String getCodEmpleado() {
        return this.codEmpleado;
    }
    
    public void setCodEmpleado(String codEmpleado) {
        this.codEmpleado = codEmpleado;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getNroIdentidad() {
        return this.nroIdentidad;
    }
    
    public void setNroIdentidad(String nroIdentidad) {
        this.nroIdentidad = nroIdentidad;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getLugarNacimiento() {
        return this.lugarNacimiento;
    }
    
    public void setLugarNacimiento(String lugarNacimiento) {
        this.lugarNacimiento = lugarNacimiento;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public BigDecimal getSueldoBruto() {
        return this.sueldoBruto;
    }
    
    public void setSueldoBruto(BigDecimal sueldoBruto) {
        this.sueldoBruto = sueldoBruto;
    }
    public Date getFecAlta() {
        return this.fecAlta;
    }
    
    public void setFecAlta(Date fecAlta) {
        this.fecAlta = fecAlta;
    }
    public Date getFecBaja() {
        return this.fecBaja;
    }
    
    public void setFecBaja(Date fecBaja) {
        this.fecBaja = fecBaja;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFecModificado() {
        return this.fecModificado;
    }
    
    public void setFecModificado(Date fecModificado) {
        this.fecModificado = fecModificado;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getTel1() {
        return this.tel1;
    }
    
    public void setTel1(String tel1) {
        this.tel1 = tel1;
    }
    public String getTel2() {
        return this.tel2;
    }
    
    public void setTel2(String tel2) {
        this.tel2 = tel2;
    }
    public String getCorreo1() {
        return this.correo1;
    }
    
    public void setCorreo1(String correo1) {
        this.correo1 = correo1;
    }
    public String getCorreo2() {
        return this.correo2;
    }
    
    public void setCorreo2(String correo2) {
        this.correo2 = correo2;
    }

 
}
