package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1



/**
 * Menurol generated by hbm2java
 */
public class Menurol  implements java.io.Serializable {


     private Integer id;
     private Rol rol;
     private int idMenu;

    public Menurol() {
    }

    public Menurol(Rol rol, int idMenu) {
       this.rol = rol;
       this.idMenu = idMenu;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public int getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(int idMenu) {
        this.idMenu = idMenu;
    }




}


