package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1



/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Integer id;
     private Byte idMenu;
     private Integer idItem;
     private String nombre;
     private Integer idNivel;
     private Character tipoItem;
     private String url;
     private String icono;

    public Menu() {
    }

	
    public Menu(String nombre) {
        this.nombre = nombre;
    }
    public Menu(Byte idMenu, Integer idItem, String nombre, Integer idNivel, Character tipoItem, String url, String icono) {
       this.idMenu = idMenu;
       this.idItem = idItem;
       this.nombre = nombre;
       this.idNivel = idNivel;
       this.tipoItem = tipoItem;
       this.url = url;
       this.icono = icono;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Byte getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(Byte idMenu) {
        this.idMenu = idMenu;
    }
    public Integer getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(Integer idItem) {
        this.idItem = idItem;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getIdNivel() {
        return this.idNivel;
    }
    
    public void setIdNivel(Integer idNivel) {
        this.idNivel = idNivel;
    }
    public Character getTipoItem() {
        return this.tipoItem;
    }
    
    public void setTipoItem(Character tipoItem) {
        this.tipoItem = tipoItem;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }




}


