package modelo;
// Generated 09-02-2019 10:41:42 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PlanMaeWkf generated by hbm2java
 */
public class PlanMaeWkf  implements java.io.Serializable {


     private Integer idPlan;
     private TbancoCtas tbancoCtas;
     private Tmoneda tmoneda;
     private int nroPlanilla;
     private int nroPeriodo;
     private int anioPeriodo;
     private String creadaPor;
     private Date fecCreacion;
     private String snRevisada;
     private Date fecRevisa;
     private String revisadaPor;
     private String snAutorizada;
     private Date fecAutorizada;
     private String autorizadaPor;
     private BigDecimal factorCambio;
     private int nroLineas;
     private String nroCheque;
     private BigDecimal impCheque;
     private BigDecimal impChequeEq;
     private String snEnviada;
     private Date fecEnviada;
     private String enviadaPor;
     private String snContabilizada;
     private Date fecContabilizacion;
     private String contabilizadaPor;
     private Date fecAnulacion;
     private String anuladaPor;
     private Set planDetWkfs = new HashSet(0);
     private Set planResWkfs = new HashSet(0);

    public PlanMaeWkf() {
    }

	
    public PlanMaeWkf(TbancoCtas tbancoCtas, Tmoneda tmoneda, int nroPlanilla, int nroPeriodo, int anioPeriodo, String creadaPor, Date fecCreacion, String snRevisada, String snAutorizada, BigDecimal factorCambio, int nroLineas, String nroCheque, BigDecimal impCheque, BigDecimal impChequeEq, String snEnviada, String snContabilizada) {
        this.tbancoCtas = tbancoCtas;
        this.tmoneda = tmoneda;
        this.nroPlanilla = nroPlanilla;
        this.nroPeriodo = nroPeriodo;
        this.anioPeriodo = anioPeriodo;
        this.creadaPor = creadaPor;
        this.fecCreacion = fecCreacion;
        this.snRevisada = snRevisada;
        this.snAutorizada = snAutorizada;
        this.factorCambio = factorCambio;
        this.nroLineas = nroLineas;
        this.nroCheque = nroCheque;
        this.impCheque = impCheque;
        this.impChequeEq = impChequeEq;
        this.snEnviada = snEnviada;
        this.snContabilizada = snContabilizada;
    }
    public PlanMaeWkf(TbancoCtas tbancoCtas, Tmoneda tmoneda, int nroPlanilla, int nroPeriodo, int anioPeriodo, String creadaPor, Date fecCreacion, String snRevisada, Date fecRevisa, String revisadaPor, String snAutorizada, Date fecAutorizada, String autorizadaPor, BigDecimal factorCambio, int nroLineas, String nroCheque, BigDecimal impCheque, BigDecimal impChequeEq, String snEnviada, Date fecEnviada, String enviadaPor, String snContabilizada, Date fecContabilizacion, String contabilizadaPor, Date fecAnulacion, String anuladaPor, Set planDetWkfs, Set planResWkfs) {
       this.tbancoCtas = tbancoCtas;
       this.tmoneda = tmoneda;
       this.nroPlanilla = nroPlanilla;
       this.nroPeriodo = nroPeriodo;
       this.anioPeriodo = anioPeriodo;
       this.creadaPor = creadaPor;
       this.fecCreacion = fecCreacion;
       this.snRevisada = snRevisada;
       this.fecRevisa = fecRevisa;
       this.revisadaPor = revisadaPor;
       this.snAutorizada = snAutorizada;
       this.fecAutorizada = fecAutorizada;
       this.autorizadaPor = autorizadaPor;
       this.factorCambio = factorCambio;
       this.nroLineas = nroLineas;
       this.nroCheque = nroCheque;
       this.impCheque = impCheque;
       this.impChequeEq = impChequeEq;
       this.snEnviada = snEnviada;
       this.fecEnviada = fecEnviada;
       this.enviadaPor = enviadaPor;
       this.snContabilizada = snContabilizada;
       this.fecContabilizacion = fecContabilizacion;
       this.contabilizadaPor = contabilizadaPor;
       this.fecAnulacion = fecAnulacion;
       this.anuladaPor = anuladaPor;
       this.planDetWkfs = planDetWkfs;
       this.planResWkfs = planResWkfs;
    }
   
    public Integer getIdPlan() {
        return this.idPlan;
    }
    
    public void setIdPlan(Integer idPlan) {
        this.idPlan = idPlan;
    }
    public TbancoCtas getTbancoCtas() {
        return this.tbancoCtas;
    }
    
    public void setTbancoCtas(TbancoCtas tbancoCtas) {
        this.tbancoCtas = tbancoCtas;
    }
    public Tmoneda getTmoneda() {
        return this.tmoneda;
    }
    
    public void setTmoneda(Tmoneda tmoneda) {
        this.tmoneda = tmoneda;
    }
    public int getNroPlanilla() {
        return this.nroPlanilla;
    }
    
    public void setNroPlanilla(int nroPlanilla) {
        this.nroPlanilla = nroPlanilla;
    }
    public int getNroPeriodo() {
        return this.nroPeriodo;
    }
    
    public void setNroPeriodo(int nroPeriodo) {
        this.nroPeriodo = nroPeriodo;
    }
    public int getAnioPeriodo() {
        return this.anioPeriodo;
    }
    
    public void setAnioPeriodo(int anioPeriodo) {
        this.anioPeriodo = anioPeriodo;
    }
    public String getCreadaPor() {
        return this.creadaPor;
    }
    
    public void setCreadaPor(String creadaPor) {
        this.creadaPor = creadaPor;
    }
    public Date getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(Date fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public String getSnRevisada() {
        return this.snRevisada;
    }
    
    public void setSnRevisada(String snRevisada) {
        this.snRevisada = snRevisada;
    }
    public Date getFecRevisa() {
        return this.fecRevisa;
    }
    
    public void setFecRevisa(Date fecRevisa) {
        this.fecRevisa = fecRevisa;
    }
    public String getRevisadaPor() {
        return this.revisadaPor;
    }
    
    public void setRevisadaPor(String revisadaPor) {
        this.revisadaPor = revisadaPor;
    }
    public String getSnAutorizada() {
        return this.snAutorizada;
    }
    
    public void setSnAutorizada(String snAutorizada) {
        this.snAutorizada = snAutorizada;
    }
    public Date getFecAutorizada() {
        return this.fecAutorizada;
    }
    
    public void setFecAutorizada(Date fecAutorizada) {
        this.fecAutorizada = fecAutorizada;
    }
    public String getAutorizadaPor() {
        return this.autorizadaPor;
    }
    
    public void setAutorizadaPor(String autorizadaPor) {
        this.autorizadaPor = autorizadaPor;
    }
    public BigDecimal getFactorCambio() {
        return this.factorCambio;
    }
    
    public void setFactorCambio(BigDecimal factorCambio) {
        this.factorCambio = factorCambio;
    }
    public int getNroLineas() {
        return this.nroLineas;
    }
    
    public void setNroLineas(int nroLineas) {
        this.nroLineas = nroLineas;
    }
    public String getNroCheque() {
        return this.nroCheque;
    }
    
    public void setNroCheque(String nroCheque) {
        this.nroCheque = nroCheque;
    }
    public BigDecimal getImpCheque() {
        return this.impCheque;
    }
    
    public void setImpCheque(BigDecimal impCheque) {
        this.impCheque = impCheque;
    }
    public BigDecimal getImpChequeEq() {
        return this.impChequeEq;
    }
    
    public void setImpChequeEq(BigDecimal impChequeEq) {
        this.impChequeEq = impChequeEq;
    }
    public String getSnEnviada() {
        return this.snEnviada;
    }
    
    public void setSnEnviada(String snEnviada) {
        this.snEnviada = snEnviada;
    }
    public Date getFecEnviada() {
        return this.fecEnviada;
    }
    
    public void setFecEnviada(Date fecEnviada) {
        this.fecEnviada = fecEnviada;
    }
    public String getEnviadaPor() {
        return this.enviadaPor;
    }
    
    public void setEnviadaPor(String enviadaPor) {
        this.enviadaPor = enviadaPor;
    }
    public String getSnContabilizada() {
        return this.snContabilizada;
    }
    
    public void setSnContabilizada(String snContabilizada) {
        this.snContabilizada = snContabilizada;
    }
    public Date getFecContabilizacion() {
        return this.fecContabilizacion;
    }
    
    public void setFecContabilizacion(Date fecContabilizacion) {
        this.fecContabilizacion = fecContabilizacion;
    }
    public String getContabilizadaPor() {
        return this.contabilizadaPor;
    }
    
    public void setContabilizadaPor(String contabilizadaPor) {
        this.contabilizadaPor = contabilizadaPor;
    }
    public Date getFecAnulacion() {
        return this.fecAnulacion;
    }
    
    public void setFecAnulacion(Date fecAnulacion) {
        this.fecAnulacion = fecAnulacion;
    }
    public String getAnuladaPor() {
        return this.anuladaPor;
    }
    
    public void setAnuladaPor(String anuladaPor) {
        this.anuladaPor = anuladaPor;
    }
    public Set getPlanDetWkfs() {
        return this.planDetWkfs;
    }
    
    public void setPlanDetWkfs(Set planDetWkfs) {
        this.planDetWkfs = planDetWkfs;
    }

    public Set getPlanResWkfs() {
        return planResWkfs;
    }

    public void setPlanResWkfs(Set planResWkfs) {
        this.planResWkfs = planResWkfs;
    }



    
    

}


