package modelo;
// Generated 09-20-2019 02:41:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PlanResWkf generated by hbm2java
 */
public class PlanResWkf  implements java.io.Serializable {


     private Integer id;
     private EmpMae empMae;
     private PlanMaeWkf planMaeWkf;
     private int periodo;
     private int anio;
     private int nroPlanilla;
     private String nroCtaBco;
     private BigDecimal impSueldoBruto;
     private BigDecimal impDebitos;
     private BigDecimal impCreditos;
     private BigDecimal impPagoNeto;
     private String snAutorizado;

    public PlanResWkf() {
    }

    public PlanResWkf(EmpMae empMae, PlanMaeWkf planMaeWkf, int periodo, int anio, int nroPlanilla, String nroCtaBco, BigDecimal impSueldoBruto, BigDecimal impDebitos, BigDecimal impCreditos, BigDecimal impPagoNeto, String snAutorizado) {
       this.empMae = empMae;
       this.planMaeWkf = planMaeWkf;
       this.periodo = periodo;
       this.anio = anio;
       this.nroPlanilla = nroPlanilla;
       this.nroCtaBco = nroCtaBco;
       this.impSueldoBruto = impSueldoBruto;
       this.impDebitos = impDebitos;
       this.impCreditos = impCreditos;
       this.impPagoNeto = impPagoNeto;
       this.snAutorizado = snAutorizado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EmpMae getEmpMae() {
        return this.empMae;
    }
    
    public void setEmpMae(EmpMae empMae) {
        this.empMae = empMae;
    }
    public PlanMaeWkf getPlanMaeWkf() {
        return this.planMaeWkf;
    }
    
    public void setPlanMaeWkf(PlanMaeWkf planMaeWkf) {
        this.planMaeWkf = planMaeWkf;
    }
    public int getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(int periodo) {
        this.periodo = periodo;
    }
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }
    public int getNroPlanilla() {
        return this.nroPlanilla;
    }
    
    public void setNroPlanilla(int nroPlanilla) {
        this.nroPlanilla = nroPlanilla;
    }
    public String getNroCtaBco() {
        return this.nroCtaBco;
    }
    
    public void setNroCtaBco(String nroCtaBco) {
        this.nroCtaBco = nroCtaBco;
    }
    public BigDecimal getImpSueldoBruto() {
        return this.impSueldoBruto;
    }
    
    public void setImpSueldoBruto(BigDecimal impSueldoBruto) {
        this.impSueldoBruto = impSueldoBruto;
    }
    public BigDecimal getImpDebitos() {
        return this.impDebitos;
    }
    
    public void setImpDebitos(BigDecimal impDebitos) {
        this.impDebitos = impDebitos;
    }
    public BigDecimal getImpCreditos() {
        return this.impCreditos;
    }
    
    public void setImpCreditos(BigDecimal impCreditos) {
        this.impCreditos = impCreditos;
    }
    public BigDecimal getImpPagoNeto() {
        return this.impPagoNeto;
    }
    
    public void setImpPagoNeto(BigDecimal impPagoNeto) {
        this.impPagoNeto = impPagoNeto;
    }
    public String getSnAutorizado() {
        return this.snAutorizado;
    }
    
    public void setSnAutorizado(String snAutorizado) {
        this.snAutorizado = snAutorizado;
    }




}


