package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {

     private Integer id;
     private String nombre;
     private String descripcion;
     private Integer estado;
     private Set usuarios = new HashSet(0);
     private Set menurols = new HashSet(0);

    public Rol() {
        this.id = 0;
    }

    public Rol(String nombre, String descripcion, Integer estado, Set usuarios, Set menurols) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estado = estado;
       this.usuarios = usuarios;
       this.menurols = menurols;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getMenurols() {
        return this.menurols;
    }
    
    public void setMenurols(Set menurols) {
        this.menurols = menurols;
    }




}


