package modelo;
// Generated 09-02-2019 10:41:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbancoCtas generated by hbm2java
 */
public class TbancoCtas  implements java.io.Serializable {


     private Integer id;
     private Tbanco tbanco;
     private Tmoneda tmoneda;
     private String nroCtaBco;
     private Set planMaeWkfs = new HashSet(0);

    public TbancoCtas() {
        //this.tbanco = new Tbanco();
       // this.tmoneda = new Tmoneda();
      //  this.id = 0;
      //  this.nroCtaBco = "";
    }

	
    public TbancoCtas(Tbanco tbanco, Tmoneda tmoneda, String nroCtaBco) {
        this.tbanco = tbanco;
        this.tmoneda = tmoneda;
        this.nroCtaBco = nroCtaBco;
    }
    public TbancoCtas(Tbanco tbanco, Tmoneda tmoneda, String nroCtaBco, Set planMaeWkfs) {
       this.tbanco = tbanco;
       this.tmoneda = tmoneda;
       this.nroCtaBco = nroCtaBco;
       this.planMaeWkfs = planMaeWkfs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tbanco getTbanco() {
        return this.tbanco;
    }
    
    public void setTbanco(Tbanco tbanco) {
        this.tbanco = tbanco;
    }
    public Tmoneda getTmoneda() {
        return this.tmoneda;
    }
    
    public void setTmoneda(Tmoneda tmoneda) {
        this.tmoneda = tmoneda;
    }
    public String getNroCtaBco() {
        return this.nroCtaBco;
    }
    
    public void setNroCtaBco(String nroCtaBco) {
        this.nroCtaBco = nroCtaBco;
    }
    public Set getPlanMaeWkfs() {
        return this.planMaeWkfs;
    }
    
    public void setPlanMaeWkfs(Set planMaeWkfs) {
        this.planMaeWkfs = planMaeWkfs;
    }




}


