package modelo;
// Generated 09-11-2019 09:41:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TdeptoPais generated by hbm2java
 */
public class TdeptoPais  implements java.io.Serializable {


     private Integer id;
     private Tpais tpais;
     private String nomDepto;
     private Set empMaes = new HashSet(0);
     private Set tmunicipioses = new HashSet(0);

    public TdeptoPais() {
        this.id = 0;
        this.tpais = new Tpais();
        this.nomDepto = "";
    }

	
    public TdeptoPais(Tpais tpais, String nomDepto) {
        this.tpais = tpais;
        this.nomDepto = nomDepto;
    }
    public TdeptoPais(Tpais tpais, String nomDepto, Set empMaes, Set tmunicipioses) {
       this.tpais = tpais;
       this.nomDepto = nomDepto;
       this.empMaes = empMaes;
       this.tmunicipioses = tmunicipioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tpais getTpais() {
        return this.tpais;
    }
    
    public void setTpais(Tpais tpais) {
        this.tpais = tpais;
    }
    public String getNomDepto() {
        return this.nomDepto;
    }
    
    public void setNomDepto(String nomDepto) {
        this.nomDepto = nomDepto;
    }
    public Set getEmpMaes() {
        return this.empMaes;
    }
    
    public void setEmpMaes(Set empMaes) {
        this.empMaes = empMaes;
    }
    public Set getTmunicipioses() {
        return this.tmunicipioses;
    }
    
    public void setTmunicipioses(Set tmunicipioses) {
        this.tmunicipioses = tmunicipioses;
    }




}


