package modelo;
// Generated 09-02-2019 10:41:42 PM by Hibernate Tools 4.3.1



/**
 * TestadosApp generated by hbm2java
 */
public class Tmeses  implements java.io.Serializable {


     private Integer id;
     private String descrip;

    public Tmeses() {
    }

    public Tmeses(String descrip) {
       this.descrip = descrip;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getDescrip() {
        return descrip;
    }

    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }
    
    
    



}


