package modelo;
// Generated 09-02-2019 10:41:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tmoneda generated by hbm2java
 */
public class Tmoneda  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Set empCtaBcos = new HashSet(0);
     private Set planMaeWkfs = new HashSet(0);
     private Set tbancoCtases = new HashSet(0);

    public Tmoneda() {
        this.id = 0;
        this.descripcion = "";
    }

    public Tmoneda(String descripcion, Set empCtaBcos, Set planMaeWkfs, Set tbancoCtases) {
       this.descripcion = descripcion;
       this.empCtaBcos = empCtaBcos;
       this.planMaeWkfs = planMaeWkfs;
       this.tbancoCtases = tbancoCtases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEmpCtaBcos() {
        return this.empCtaBcos;
    }
    
    public void setEmpCtaBcos(Set empCtaBcos) {
        this.empCtaBcos = empCtaBcos;
    }
    public Set getPlanMaeWkfs() {
        return this.planMaeWkfs;
    }
    
    public void setPlanMaeWkfs(Set planMaeWkfs) {
        this.planMaeWkfs = planMaeWkfs;
    }
    public Set getTbancoCtases() {
        return this.tbancoCtases;
    }
    
    public void setTbancoCtases(Set tbancoCtases) {
        this.tbancoCtases = tbancoCtases;
    }




}


