package modelo;
// Generated 09-11-2019 10:06:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tmunicipios generated by hbm2java
 */
public class Tmunicipios  implements java.io.Serializable {


     private Integer id;
     private TdeptoPais tdeptoPais;
     private int idPais;
     private String nomMuni;
     private String codMunicipio;
     private Set empMaes = new HashSet(0);

    public Tmunicipios() {
    }

	
    public Tmunicipios(TdeptoPais tdeptoPais, int idPais, String nomMuni, String codMunicipio) {
        this.tdeptoPais = tdeptoPais;
        this.idPais = idPais;
        this.nomMuni = nomMuni;
        this.codMunicipio = codMunicipio;
    }
    public Tmunicipios(TdeptoPais tdeptoPais, int idPais, String nomMuni, String codMunicipio, Set empMaes) {
       this.tdeptoPais = tdeptoPais;
       this.idPais = idPais;
       this.nomMuni = nomMuni;
       this.codMunicipio = codMunicipio;
       this.empMaes = empMaes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TdeptoPais getTdeptoPais() {
        return this.tdeptoPais;
    }
    
    public void setTdeptoPais(TdeptoPais tdeptoPais) {
        this.tdeptoPais = tdeptoPais;
    }
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }
    public String getNomMuni() {
        return this.nomMuni;
    }
    
    public void setNomMuni(String nomMuni) {
        this.nomMuni = nomMuni;
    }
    public String getCodMunicipio() {
        return this.codMunicipio;
    }
    
    public void setCodMunicipio(String codMunicipio) {
        this.codMunicipio = codMunicipio;
    }
    public Set getEmpMaes() {
        return this.empMaes;
    }
    
    public void setEmpMaes(Set empMaes) {
        this.empMaes = empMaes;
    }




}


