package modelo;
// Generated 09-11-2019 09:41:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tpais generated by hbm2java
 */
public class Tpais  implements java.io.Serializable {


     private Integer id;
     private String nomPais;
     private Set empMaes = new HashSet(0);
     private Set tdeptoPaises = new HashSet(0);

    public Tpais() {
    }

	
    public Tpais(String nomPais) {
        this.nomPais = nomPais;
    }
    public Tpais(String nomPais, Set empMaes, Set tdeptoPaises) {
       this.nomPais = nomPais;
       this.empMaes = empMaes;
       this.tdeptoPaises = tdeptoPaises;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomPais() {
        return this.nomPais;
    }
    
    public void setNomPais(String nomPais) {
        this.nomPais = nomPais;
    }
    public Set getEmpMaes() {
        return this.empMaes;
    }
    
    public void setEmpMaes(Set empMaes) {
        this.empMaes = empMaes;
    }
    public Set getTdeptoPaises() {
        return this.tdeptoPaises;
    }
    
    public void setTdeptoPaises(Set tdeptoPaises) {
        this.tdeptoPaises = tdeptoPaises;
    }




}


