package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;


/**
 * Tprofesion generated by hbm2java
 */
public class Tprofesion implements java.io.Serializable {

    private Integer id;
    private String nomProfesion;
    private Set empMaes = new HashSet(0);
    
    public Tprofesion() {

        this.id = 0;
         this.nomProfesion = "";
      
    }
    
     public Tprofesion(String nomProfesion, Set empMaes) {
       this.nomProfesion = nomProfesion;
       this.empMaes = empMaes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomProfesion() {
        return this.nomProfesion;
    }
    
    public void setNomProfesion(String nomProfesion) {
        this.nomProfesion = nomProfesion;
    }
    public Set getEmpMaes() {
        return this.empMaes;
    }
    
    public void setEmpMaes(Set empMaes) {
        this.empMaes = empMaes;
    }


    
}
