package modelo;
// Generated 09-02-2019 10:41:42 PM by Hibernate Tools 4.3.1



/**
 * TtipoPlanilla generated by hbm2java
 */
public class TtipoPlanilla  implements java.io.Serializable {


     private Integer id;
     private String desc;

    public TtipoPlanilla() {
    }

    public TtipoPlanilla(String desc) {
       this.desc = desc;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }




}


